// entityBrowser.js - Entity Browser Tool for BIRAVA2025
//
// ARCHITECTURAL PURPOSE: Provides comprehensive web interface for querying and managing
// the collection-based entity system. This tool replaces individual file management
// (1,400+ files) with efficient collection browsing (3 files) and enables interactive
// search across all 30 CSV fields captured by the enhanced processing system.
//
// INTEGRATION: Works directly with collection files generated by aggregateEntitiesIntoCollections()
// function in bloomerang.js, providing seamless access to all processed entity data.

// Global state management for Entity Browser Tool
// Maintains collection data in memory for fast search and filtering operations
const entityBrowser = {
    collections: {
        individuals: null,    // Individual entity collection with enhanced 30-field data
        households: null,     // Household entity collection with member relationships
        nonhuman: null       // Business/legal entity collection
    },
    currentCollection: 'individuals',  // Currently active collection for browsing
    currentResults: [],                 // Filtered search results for display
    selectedEntity: null               // Currently selected entity for detailed viewing
};

/**
 * Switch between collection types (Individuals, Households, NonHuman)
 */
function switchCollection(collectionType) {
    // Update UI tabs
    document.querySelectorAll('.collection-tab').forEach(tab => {
        tab.classList.remove('active');
    });
    event.target.classList.add('active');

    // Update current collection
    entityBrowser.currentCollection = collectionType;

    // Clear search and show all entities in new collection
    document.getElementById('searchInput').value = '';
    showAll();
}

/**
 * Load all entity collections from Google Drive for interactive browsing
 *
 * PERFORMANCE IMPACT: This single operation loads all entity data (1,362 entities, 426 households)
 * into memory, enabling instant search and filtering without additional API calls. This replaces
 * the need for 1,400+ individual file requests with just 3 collection file loads.
 *
 * COLLECTION ARCHITECTURE: Loads the three collection files generated by the enhanced
 * processing system, each containing comprehensive entity data with all 30 CSV fields,
 * structured indexes, and metadata for efficient querying.
 *
 * @returns {Promise<void>} Resolves when all collections are loaded into entityBrowser.collections
 */
async function loadCollections() {
    showStatus('Loading collections from Google Drive...', 'loading');

    try {
        // Collection file IDs from aggregateEntitiesIntoCollections() uploads
        // These contain all processed entities with enhanced 30-field data structure
        const fileIds = {
            individuals: '1PFPkHqc5aQmeJPmZwcsUVHgKMftiqS3e', // Individual entities with comprehensive data
            households: '1f0RebTi4EqpO6fHTNYyZyTQ8Gthbkvmi',   // Household entities with member relationships
            nonhuman: '1ze_s1AwwIuKHaVOK0cVbXN49mR0CS-ke'      // Business and legal entities
        };

        // Load each collection file and parse JSON data
        // Each collection contains: entities object, metadata, and search indexes
        for (const [type, fileId] of Object.entries(fileIds)) {
            try {
                console.log(`Loading ${type} collection...`);
                const response = await gapi.client.drive.files.get({
                    fileId: fileId,
                    alt: 'media'
                });

                const collectionData = JSON.parse(response.body);
                entityBrowser.collections[type] = collectionData;
                console.log(`✅ Loaded ${type}:`, collectionData.metadata.totalEntities, 'entities');

            } catch (error) {
                console.warn(`Failed to load ${type} collection:`, error);
                showStatus(`Warning: Could not load ${type} collection`, 'error');
            }
        }

        showStatus('Collections loaded successfully!', 'success');

        // Show current collection
        showAll();

    } catch (error) {
        console.error('Error loading collections:', error);
        showStatus('Error loading collections. Make sure you\'re authenticated with Google Drive.', 'error');
    }
}

/**
 * Show all entities in current collection
 */
function showAll() {
    const collection = entityBrowser.collections[entityBrowser.currentCollection];

    if (!collection) {
        showStatus('Collection not loaded. Click "Load Collections" first.', 'error');
        return;
    }

    const entities = Object.entries(collection.entities);
    displayResults(entities);

    document.getElementById('resultsCount').textContent =
        `Showing all ${entities.length} ${entityBrowser.currentCollection}`;
}

/**
 * Perform search across current collection
 */
function performSearch() {
    const query = document.getElementById('searchInput').value.trim().toLowerCase();

    if (!query) {
        showAll();
        return;
    }

    const collection = entityBrowser.collections[entityBrowser.currentCollection];
    if (!collection) {
        showStatus('Collection not loaded. Click "Load Collections" first.', 'error');
        return;
    }

    const results = [];

    // Search through entities
    for (const [key, entity] of Object.entries(collection.entities)) {
        if (entityMatchesQuery(key, entity, query)) {
            results.push([key, entity]);
        }
    }

    displayResults(results);
    document.getElementById('resultsCount').textContent =
        `Found ${results.length} results for "${query}"`;
}

/**
 * Check if entity matches search query across all available data
 *
 * SEARCH STRATEGY: Performs comprehensive search across both entity keys and all entity data
 * including the enhanced 30-field structure (transaction data, addresses, Block Island fields).
 * Uses JSON string conversion for deep search across nested object structures.
 *
 * PERFORMANCE NOTE: While JSON.stringify() is not the most efficient search method for large
 * datasets, it provides comprehensive coverage of all fields and works well for the current
 * dataset size (~1,400 entities). Future optimization could implement indexed field searches.
 *
 * @param {string} key - Entity key (account_123, fire_456, etc.)
 * @param {Object} entity - Complete entity object with all data fields
 * @param {string} query - Search query string (case-insensitive)
 * @returns {boolean} True if entity matches query in key or data fields
 */
function entityMatchesQuery(key, entity, query) {
    // First check entity key for direct matches (account numbers, fire numbers)
    if (key.toLowerCase().includes(query)) return true;

    // Deep search across all entity data including:
    // - Core fields (names, account numbers, location identifiers)
    // - Contact information (email, PO boxes, BI addresses)
    // - Transaction data (amounts, dates)
    // - All address types (primary, home, vacation, work)
    // - Block Island specific data (fire numbers, BI fields)
    // - Household data (household names, membership status)
    const entityStr = JSON.stringify(entity).toLowerCase();
    return entityStr.includes(query);
}

/**
 * Quick filter functions
 */
function quickFilter(filterType) {
    const collection = entityBrowser.collections[entityBrowser.currentCollection];
    if (!collection) {
        showStatus('Collection not loaded. Click "Load Collections" first.', 'error');
        return;
    }

    let results = [];
    const entities = Object.entries(collection.entities);

    switch (filterType) {
        case 'account':
            results = entities.filter(([key]) => key.startsWith('account_'));
            break;
        case 'fire':
            results = entities.filter(([key]) => key.startsWith('fire_'));
            break;
        case 'name':
            // Show entities with name information
            results = entities.filter(([key, entity]) => {
                return entity.name && entity.name.identifier;
            });
            break;
        default:
            results = entities;
    }

    displayResults(results);
    document.getElementById('resultsCount').textContent =
        `Showing ${results.length} entities filtered by ${filterType}`;
}

/**
 * Display search results in the UI
 */
function displayResults(results) {
    const resultsList = document.getElementById('resultsList');

    if (results.length === 0) {
        resultsList.innerHTML = '<div style="padding: 20px; text-align: center; color: #666;">No results found</div>';
        return;
    }

    const html = results.map(([key, entity]) => {
        const entityName = extractEntityName(entity);
        const entityDetails = extractEntityDetails(entity);

        return `
            <div class="result-item" onclick="selectEntity('${key}', this)">
                <div class="entity-key">${key}</div>
                <div class="entity-name">${entityName}</div>
                <div class="entity-details">${entityDetails}</div>
            </div>
        `;
    }).join('');

    resultsList.innerHTML = html;
    entityBrowser.currentResults = results;
}

/**
 * Extract display name from entity
 */
function extractEntityName(entity) {
    if (!entity.name || !entity.name.identifier) return 'Unknown';

    const nameObj = entity.name.identifier;

    if (nameObj.completeName) {
        return nameObj.completeName;
    }

    if (nameObj.fullName) {
        return nameObj.fullName;
    }

    if (nameObj.firstName && nameObj.lastName) {
        return `${nameObj.firstName} ${nameObj.lastName}`;
    }

    return 'Name available';
}

/**
 * Extract entity details for display
 */
function extractEntityDetails(entity) {
    const details = [];

    // Add location info
    if (entity.locationIdentifier && entity.locationIdentifier.identifier) {
        const locId = entity.locationIdentifier.identifier;
        if (locId.primaryAlias) {
            const locType = locId.constructor?.name || 'Location';
            details.push(`${locType}: ${locId.primaryAlias.term}`);
        }
    }

    // Add account number
    if (entity.accountNumber && entity.accountNumber.identifier && entity.accountNumber.identifier.primaryAlias) {
        details.push(`Account: ${entity.accountNumber.identifier.primaryAlias.term}`);
    }

    return details.join(' | ') || 'Details available';
}

/**
 * Select an entity for detailed viewing
 */
function selectEntity(key, element) {
    // Remove previous selection
    document.querySelectorAll('.result-item').forEach(item => {
        item.style.backgroundColor = '';
    });

    // Highlight selected item
    element.style.backgroundColor = '#e3f2fd';

    // Store selected entity
    const entity = entityBrowser.currentResults.find(([k]) => k === key)?.[1];
    entityBrowser.selectedEntity = { key, entity };
}

/**
 * View selected entity details
 */
function viewSelectedEntity() {
    if (!entityBrowser.selectedEntity) {
        showStatus('Please select an entity first', 'error');
        return;
    }

    const { key, entity } = entityBrowser.selectedEntity;

    // Create detailed view
    const detailsWindow = window.open('', '_blank', 'width=800,height=600,scrollbars=yes');
    detailsWindow.document.write(`
        <html>
            <head><title>Entity Details: ${key}</title></head>
            <body style="font-family: Arial, sans-serif; padding: 20px;">
                <h2>Entity Details</h2>
                <p><strong>Key:</strong> ${key}</p>
                <h3>Full Entity Data:</h3>
                <pre style="background-color: #f4f4f4; padding: 15px; border-radius: 5px; overflow: auto;">
${JSON.stringify(entity, null, 2)}
                </pre>
            </body>
        </html>
    `);
    detailsWindow.document.close();
}

/**
 * Export current results
 */
function exportResults() {
    if (entityBrowser.currentResults.length === 0) {
        showStatus('No results to export', 'error');
        return;
    }

    const exportData = {
        collection: entityBrowser.currentCollection,
        exportedAt: new Date().toISOString(),
        totalResults: entityBrowser.currentResults.length,
        results: entityBrowser.currentResults.map(([key, entity]) => ({
            key,
            entity
        }))
    };

    const blob = new Blob([JSON.stringify(exportData, null, 2)],
                         { type: 'application/json' });
    const url = URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.href = url;
    a.download = `birava_${entityBrowser.currentCollection}_export_${new Date().toISOString().split('T')[0]}.json`;
    a.click();

    URL.revokeObjectURL(url);
    showStatus(`Exported ${entityBrowser.currentResults.length} results`, 'success');
}

/**
 * Show index statistics for current collection
 */
function showIndexStats() {
    const collection = entityBrowser.collections[entityBrowser.currentCollection];
    if (!collection) {
        showStatus('Collection not loaded. Click "Load Collections" first.', 'error');
        return;
    }

    const stats = collection.index;
    let statsHtml = `
        <h3>Index Statistics - ${entityBrowser.currentCollection}</h3>
        <ul>
    `;

    for (const [indexName, indexData] of Object.entries(stats)) {
        if (typeof indexData === 'object' && indexData !== null) {
            const count = Array.isArray(indexData) ? indexData.length : Object.keys(indexData).length;
            statsHtml += `<li><strong>${indexName}:</strong> ${count} entries</li>`;
        } else {
            statsHtml += `<li><strong>${indexName}:</strong> ${indexData}</li>`;
        }
    }

    statsHtml += '</ul>';

    const statsWindow = window.open('', '_blank', 'width=600,height=400,scrollbars=yes');
    statsWindow.document.write(`
        <html>
            <head><title>Index Statistics</title></head>
            <body style="font-family: Arial, sans-serif; padding: 20px;">
                ${statsHtml}
            </body>
        </html>
    `);
    statsWindow.document.close();
}

/**
 * Clear search input and show all
 */
function clearSearch() {
    document.getElementById('searchInput').value = '';
    showAll();
}

/**
 * Handle Enter key in search input
 */
function handleSearchKeyPress(event) {
    if (event.key === 'Enter') {
        performSearch();
    }
}

/**
 * Show status message
 */
function showStatus(message, type) {
    const statusElement = document.getElementById('statusMessage');
    statusElement.textContent = message;
    statusElement.className = `status-message status-${type}`;
    statusElement.style.display = 'block';

    // Auto-hide success messages after 3 seconds
    if (type === 'success') {
        setTimeout(() => {
            statusElement.style.display = 'none';
        }, 3000);
    }
}